services:
  mongo:
    image: mongo
    # ports:
    #   - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
  
  redis:
    image: redis
    # ports:
    #   - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
  backend:
    image: hello-backend-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    container_name: hello-back
    depends_on:
      - mongo
      - redis
  app:
    image: hello-front-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile 
    container_name: hello-front
    depends_on:
      - backend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - backend