services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: phonebook
    volumes: 
      - ./phonebook-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./phonebook-backend/mongo_data:/data/db
  
  backend:
    image: phonebook-backend
    build:
      context: ./phonebook-backend
      dockerfile: Dockerfile
    container_name: phonebook-back
    volumes:
      - ./phonebook-backend:/usr/src/app 
    depends_on:
      - mongo
  app:
    image: phonebook-frontend
    build:
      context: ./phonebook-frontend
      dockerfile: Dockerfile 
    container_name: phonebook-front
    depends_on:
      - backend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - backend